### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by okoyecharles** [ishpaul777/Leaderboard#4]
# Status: Changes Required 🔴 🔴 🔴

Hey @ishpaul777, 
I think your code looks great but there are some changes that would make it even better.

# Highlights
- Very descriptive readme file and pull request message ✔️
- Good commit messages ✔️
- No linter errors ✔
- You followed Javascript best practices ✔️

# Required Changes:

## Video explanation

https://user-images.githubusercontent.com/102174805/197224051-c9322d51-5bab-4a93-8537-671fe49ae16f.mp4

Remember that feedback is a positive thing even if it feels a bit unpleasant.
> Check the comments below for descriptive changes that are required.

- [x] As shown below, I don't think it is good javascript practice to manipulate the DOM all around, I suggest you use a function to separate (and preferably put it in the index.js)
https://github.com/ishpaul777/Leaderboard/blob/881c408796be37ff4a01cdb2c37159a0ff60365c/src/submitScore.js#L15
----------------------------------------

- [x] As shown below you used an async function when it was not necessary (you only use async functions when you need asynchronous, non-blocking functionality e.g. Fetching data from an api)
https://github.com/ishpaul777/Leaderboard/blob/881c408796be37ff4a01cdb2c37159a0ff60365c/src/addScore.js#L3-L11
---------------------------------------

- [x] **OPTIONAL:** I recommend you separate your event listener's functionality with separate functions (It makes your code easier to read and understand)
https://github.com/ishpaul777/Leaderboard/blob/881c408796be37ff4a01cdb2c37159a0ff60365c/src/index.js#L11-L18
-----------------------------------------

- [x] **OPTIONAL:** Don't forget adding a few comments here and there would go a long way to making your code even more understandable, I suggest you add them.

**Comment by ishpaul777** [comment]
![ThankYouThankYouThankYouGifkaroGIF](https://user-images.githubusercontent.com/104348397/180157689-4466d5b7-59ed-458a-82f8-bb16966dcaa2.gif)
.

Thank you so much! For the review. I will work on the issues
